name: Build Maven

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 1.8 e Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8.0.332+9'
          cache: 'maven'
      - name: Build Maven
        run: mvn -B clean install --file pom.xml 